# Generated by Django 5.0.4 on 2024-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='option_details',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('qust_d_id', models.IntegerField()),
                ('option', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=1)),
                ('is_enabled', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='question_details',
            fields=[
                ('qust_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('qust_id', models.IntegerField()),
                ('questions', models.CharField(max_length=500, unique=True)),
                ('qust_type', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('parent_id', models.IntegerField(default=0)),
                ('is_enabled', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='question_master',
            fields=[
                ('qust_id', models.AutoField(primary_key=True, serialize=False)),
                ('qust_title', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='survey_ans',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('qust_id', models.IntegerField()),
                ('option_id', models.IntegerField()),
                ('image_path', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
