# Generated by Django 5.0.4 on 2024-05-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_details',
            name='qust_type',
        ),
        migrations.AlterField(
            model_name='question_details',
            name='questions',
            field=models.CharField(max_length=500),
        ),
    ]
