# Generated by Django 5.0.4 on 2024-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_question_details_qust_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_details',
            name='qust_type',
            field=models.IntegerField(default=1),
        ),
    ]
