# Generated by Django 5.0.4 on 2024-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_question_details_qust_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_details',
            name='option',
            field=models.CharField(max_length=100),
        ),
    ]
