# Generated by Django 5.0.4 on 2024-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_option_details_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_to',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_time',
            field=models.DateTimeField(default='00/00/0000 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option_details',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question_master',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
    ]
